# Generated by Django 3.1.7 on 2021-09-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='.', max_length=100, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('fantasia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fantasia')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, unique=True, verbose_name='CPF/CNPJ')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('complemento', models.CharField(blank=True, max_length=35, null=True, verbose_name='Complemento')),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Logradouro')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('fone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fone')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['nome'],
            },
        ),
    ]
